'use client';

import { useParams } from 'next/navigation';
import { useEffect, useState } from 'react';
import { Map, Clock, DollarSign, Award, Loader2, BarChart3, Star, Shield, Smile } from 'lucide-react';

interface TripRecord {
  id?: string;
  duration: number;
  tier: string;
  regions: string[];
  cost: number;
  safety: number;
  enjoyment: number;
  overall: number;
}

interface TripsData {
  records: TripRecord[];
  total: number;
  avgDuration: number;
  avgCost: number;
  tierDistribution: Record<string, number>;
  regionDistribution: Record<string, number>;
}

function SkeletonCard() {
  return (
    <div className="bg-white rounded-2xl shadow-sm border border-gray-100 p-5 animate-pulse">
      <div className="h-4 bg-gray-100 rounded w-20 mb-3" />
      <div className="h-8 bg-gray-100 rounded w-16 mb-1" />
      <div className="h-3 bg-gray-50 rounded w-24" />
    </div>
  );
}

function SkeletonRow() {
  return (
    <tr className="border-b border-gray-50">
      {Array.from({ length: 7 }).map((_, i) => (
        <td key={i} className="px-6 py-4">
          <div className="h-4 bg-gray-100 rounded animate-pulse" style={{ width: '60%' }} />
        </td>
      ))}
    </tr>
  );
}

export default function TripsPage() {
  const params = useParams();
  const locale = (params.locale as string) || 'en';
  const isRtl = locale === 'ar';

  const [data, setData] = useState<TripsData | null>(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);

  useEffect(() => {
    async function fetchTrips() {
      try {
        setLoading(true);
        const res = await fetch('/api/admin/trips');
        if (!res.ok) throw new Error(`Failed to fetch: ${res.status}`);
        const json = await res.json();
        setData({
          records: json.records || [],
          total: json.total ?? 0,
          avgDuration: json.avgDuration ?? 0,
          avgCost: json.avgCost ?? 0,
          tierDistribution: json.tierDistribution ?? {},
          regionDistribution: json.regionDistribution ?? {},
        });
      } catch (err) {
        setError(err instanceof Error ? err.message : 'Unknown error');
      } finally {
        setLoading(false);
      }
    }
    fetchTrips();
  }, []);

  const textAlign = isRtl ? 'text-right' : 'text-left';

  function getMostPopularTier(): string {
    if (!data || !data.tierDistribution) return '-';
    const entries = Object.entries(data.tierDistribution);
    if (entries.length === 0) return '-';
    entries.sort((a, b) => b[1] - a[1]);
    const tier = entries[0][0];
    return tier.charAt(0).toUpperCase() + tier.slice(1);
  }

  function formatCost(cost: number): string {
    return `${cost.toFixed(1)} OMR`;
  }

  function scoreColor(score: number): string {
    if (score >= 8) return 'text-green-600';
    if (score >= 5) return 'text-amber-600';
    return 'text-red-500';
  }

  return (
    <div className="space-y-6" dir={isRtl ? 'rtl' : 'ltr'}>
      {/* Header */}
      <div>
        <h1 className={`text-2xl font-bold text-gray-900 ${textAlign}`}>
          {isRtl ? 'تحليلات الرحلات' : 'Trip Analytics'}
        </h1>
        <p className={`text-sm text-gray-500 mt-1 ${textAlign}`}>
          {isRtl
            ? 'نظرة عامة على خطط الرحلات التي أنشأها المستخدمون'
            : 'Overview of trip plans generated by users'}
        </p>
      </div>

      {/* Error */}
      {error && (
        <div className="bg-red-50 border border-red-200 rounded-2xl p-6 text-center">
          <p className="text-sm text-red-600">{isRtl ? 'خطأ في تحميل البيانات' : 'Error loading data'}: {error}</p>
        </div>
      )}

      {/* Loading Skeleton */}
      {loading && (
        <>
          <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-4">
            {Array.from({ length: 4 }).map((_, i) => (
              <SkeletonCard key={i} />
            ))}
          </div>
          <div className="bg-white rounded-2xl shadow-sm border border-gray-100 overflow-hidden">
            <div className="px-6 py-4 border-b border-gray-100 bg-gray-50/60 flex items-center gap-2">
              <Loader2 size={16} className="text-gray-400 animate-spin" />
              <span className="text-sm text-gray-500">{isRtl ? 'جاري التحميل...' : 'Loading trip data...'}</span>
            </div>
            <table className="w-full text-sm">
              <thead>
                <tr className="border-b border-gray-100">
                  {[
                    isRtl ? 'المدة' : 'Duration',
                    isRtl ? 'الفئة' : 'Tier',
                    isRtl ? 'المناطق' : 'Regions',
                    isRtl ? 'التكلفة' : 'Cost',
                    isRtl ? 'الأمان' : 'Safety',
                    isRtl ? 'المتعة' : 'Enjoyment',
                    isRtl ? 'الإجمالي' : 'Overall',
                  ].map((label) => (
                    <th key={label} className={`px-6 py-3 font-medium text-gray-500 ${textAlign}`}>{label}</th>
                  ))}
                </tr>
              </thead>
              <tbody>
                {Array.from({ length: 4 }).map((_, i) => (
                  <SkeletonRow key={i} />
                ))}
              </tbody>
            </table>
          </div>
        </>
      )}

      {/* Loaded Content */}
      {!loading && !error && data && (
        <>
          {/* KPI Cards */}
          <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-4">
            <div className="bg-white rounded-2xl shadow-sm border border-gray-100 p-5">
              <div className={`flex items-center gap-3 ${isRtl ? 'flex-row-reverse' : ''}`}>
                <div className="bg-blue-50 p-2.5 rounded-xl">
                  <BarChart3 size={20} className="text-blue-600" />
                </div>
                <div className={textAlign}>
                  <p className="text-2xl font-bold text-gray-900">{data.total}</p>
                  <p className="text-xs text-gray-500">{isRtl ? 'إجمالي الخطط' : 'Total Plans'}</p>
                </div>
              </div>
            </div>

            <div className="bg-white rounded-2xl shadow-sm border border-gray-100 p-5">
              <div className={`flex items-center gap-3 ${isRtl ? 'flex-row-reverse' : ''}`}>
                <div className="bg-teal-50 p-2.5 rounded-xl">
                  <Clock size={20} className="text-teal-600" />
                </div>
                <div className={textAlign}>
                  <p className="text-2xl font-bold text-gray-900">
                    {data.avgDuration.toFixed(1)} {isRtl ? 'يوم' : 'days'}
                  </p>
                  <p className="text-xs text-gray-500">{isRtl ? 'متوسط المدة' : 'Avg Duration'}</p>
                </div>
              </div>
            </div>

            <div className="bg-white rounded-2xl shadow-sm border border-gray-100 p-5">
              <div className={`flex items-center gap-3 ${isRtl ? 'flex-row-reverse' : ''}`}>
                <div className="bg-amber-50 p-2.5 rounded-xl">
                  <DollarSign size={20} className="text-amber-600" />
                </div>
                <div className={textAlign}>
                  <p className="text-2xl font-bold text-gray-900">{formatCost(data.avgCost)}</p>
                  <p className="text-xs text-gray-500">{isRtl ? 'متوسط التكلفة' : 'Avg Cost'}</p>
                </div>
              </div>
            </div>

            <div className="bg-white rounded-2xl shadow-sm border border-gray-100 p-5">
              <div className={`flex items-center gap-3 ${isRtl ? 'flex-row-reverse' : ''}`}>
                <div className="bg-purple-50 p-2.5 rounded-xl">
                  <Award size={20} className="text-purple-600" />
                </div>
                <div className={textAlign}>
                  <p className="text-2xl font-bold text-gray-900">{getMostPopularTier()}</p>
                  <p className="text-xs text-gray-500">{isRtl ? 'الفئة الأكثر شعبية' : 'Most Popular Tier'}</p>
                </div>
              </div>
            </div>
          </div>

          {/* Empty State */}
          {data.total === 0 && (
            <div className="bg-white rounded-2xl shadow-sm border border-gray-100 p-12 flex flex-col items-center justify-center text-center">
              <div className="w-16 h-16 bg-gray-100 rounded-2xl flex items-center justify-center mb-6">
                <Map size={28} className="text-gray-400" />
              </div>
              <h2 className="text-lg font-semibold text-gray-900 mb-2">
                {isRtl ? 'لا توجد رحلات بعد' : 'No trips generated yet'}
              </h2>
              <p className="text-sm text-gray-500 max-w-md leading-relaxed">
                {isRtl
                  ? 'ستظهر الخطط هنا عندما ينشئ المستخدمون مسارات عبر المخطط أو الدردشة الذكية.'
                  : 'Plans will appear here as users create itineraries via the planner or Smart Chat.'}
              </p>
            </div>
          )}

          {/* Records Table */}
          {data.total > 0 && data.records.length > 0 && (
            <div className="bg-white rounded-2xl shadow-sm border border-gray-100 overflow-hidden">
              <div className={`px-6 py-4 border-b border-gray-100 bg-gray-50/60 ${textAlign}`}>
                <div className={`flex items-center gap-2 ${isRtl ? 'flex-row-reverse' : ''}`}>
                  <Map size={16} className="text-gray-500" />
                  <h2 className="text-sm font-semibold text-gray-900">
                    {isRtl ? 'سجلات الرحلات' : 'Trip Records'}
                  </h2>
                  <span className="text-xs text-gray-400 ml-2">({data.records.length})</span>
                </div>
              </div>

              {/* Desktop table */}
              <div className="hidden md:block overflow-x-auto">
                <table className="w-full text-sm">
                  <thead>
                    <tr className="border-b border-gray-100">
                      <th className={`px-6 py-3 font-medium text-gray-500 ${textAlign}`}>
                        {isRtl ? 'المدة' : 'Duration'}
                      </th>
                      <th className={`px-6 py-3 font-medium text-gray-500 ${textAlign}`}>
                        {isRtl ? 'الفئة' : 'Tier'}
                      </th>
                      <th className={`px-6 py-3 font-medium text-gray-500 ${textAlign}`}>
                        {isRtl ? 'المناطق' : 'Regions'}
                      </th>
                      <th className={`px-6 py-3 font-medium text-gray-500 ${textAlign}`}>
                        {isRtl ? 'التكلفة' : 'Cost'}
                      </th>
                      <th className={`px-6 py-3 font-medium text-gray-500 ${textAlign}`}>
                        <div className={`flex items-center gap-1 ${isRtl ? 'flex-row-reverse' : ''}`}>
                          <Shield size={13} />
                          {isRtl ? 'الأمان' : 'Safety'}
                        </div>
                      </th>
                      <th className={`px-6 py-3 font-medium text-gray-500 ${textAlign}`}>
                        <div className={`flex items-center gap-1 ${isRtl ? 'flex-row-reverse' : ''}`}>
                          <Smile size={13} />
                          {isRtl ? 'المتعة' : 'Enjoyment'}
                        </div>
                      </th>
                      <th className={`px-6 py-3 font-medium text-gray-500 ${textAlign}`}>
                        <div className={`flex items-center gap-1 ${isRtl ? 'flex-row-reverse' : ''}`}>
                          <Star size={13} />
                          {isRtl ? 'الإجمالي' : 'Overall'}
                        </div>
                      </th>
                    </tr>
                  </thead>
                  <tbody>
                    {data.records.map((record, idx) => (
                      <tr key={record.id || idx} className="border-b border-gray-50 hover:bg-gray-50/50 transition-colors">
                        <td className={`px-6 py-3 text-sm text-gray-700 ${textAlign}`}>
                          {record.duration} {isRtl ? 'يوم' : record.duration === 1 ? 'day' : 'days'}
                        </td>
                        <td className={`px-6 py-3 ${textAlign}`}>
                          <span className="inline-block px-2.5 py-0.5 bg-blue-50 text-blue-700 rounded-full text-xs font-medium capitalize">
                            {record.tier}
                          </span>
                        </td>
                        <td className={`px-6 py-3 ${textAlign}`}>
                          <div className={`flex flex-wrap gap-1 ${isRtl ? 'flex-row-reverse' : ''}`}>
                            {record.regions.map((region) => (
                              <span
                                key={region}
                                className="inline-block px-2 py-0.5 bg-gray-100 text-gray-600 rounded-full text-xs"
                              >
                                {region}
                              </span>
                            ))}
                          </div>
                        </td>
                        <td className={`px-6 py-3 text-sm text-gray-700 font-medium ${textAlign}`}>
                          {formatCost(record.cost)}
                        </td>
                        <td className={`px-6 py-3 text-sm font-semibold ${scoreColor(record.safety)} ${textAlign}`}>
                          {record.safety.toFixed(1)}
                        </td>
                        <td className={`px-6 py-3 text-sm font-semibold ${scoreColor(record.enjoyment)} ${textAlign}`}>
                          {record.enjoyment.toFixed(1)}
                        </td>
                        <td className={`px-6 py-3 text-sm font-semibold ${scoreColor(record.overall)} ${textAlign}`}>
                          {record.overall.toFixed(1)}
                        </td>
                      </tr>
                    ))}
                  </tbody>
                </table>
              </div>

              {/* Mobile cards */}
              <div className="md:hidden divide-y divide-gray-50">
                {data.records.map((record, idx) => (
                  <div key={record.id || idx} className={`px-5 py-4 ${textAlign}`}>
                    <div className={`flex items-center justify-between mb-2 ${isRtl ? 'flex-row-reverse' : ''}`}>
                      <span className="inline-block px-2.5 py-0.5 bg-blue-50 text-blue-700 rounded-full text-xs font-medium capitalize">
                        {record.tier}
                      </span>
                      <span className="text-sm font-medium text-gray-700">
                        {record.duration} {isRtl ? 'يوم' : record.duration === 1 ? 'day' : 'days'}
                      </span>
                    </div>
                    <div className={`flex flex-wrap gap-1 mb-2 ${isRtl ? 'flex-row-reverse' : ''}`}>
                      {record.regions.map((region) => (
                        <span
                          key={region}
                          className="inline-block px-2 py-0.5 bg-gray-100 text-gray-600 rounded-full text-xs"
                        >
                          {region}
                        </span>
                      ))}
                    </div>
                    <div className={`flex items-center gap-4 text-xs ${isRtl ? 'flex-row-reverse' : ''}`}>
                      <span className="text-gray-700 font-medium">{formatCost(record.cost)}</span>
                      <span className={`font-semibold ${scoreColor(record.safety)}`}>
                        {isRtl ? 'أمان' : 'Safety'} {record.safety.toFixed(1)}
                      </span>
                      <span className={`font-semibold ${scoreColor(record.enjoyment)}`}>
                        {isRtl ? 'متعة' : 'Enjoy'} {record.enjoyment.toFixed(1)}
                      </span>
                      <span className={`font-semibold ${scoreColor(record.overall)}`}>
                        {isRtl ? 'إجمالي' : 'Overall'} {record.overall.toFixed(1)}
                      </span>
                    </div>
                  </div>
                ))}
              </div>
            </div>
          )}
        </>
      )}
    </div>
  );
}
